-- V6: Configuração do sistema
-- Guarda ajustes editáveis pelo ADMIN sem precisar recompilar/redeployar.
-- Hoje só a lista de atributos padrão do chat (antes hardcoded no
-- ChatService); a tabela é desenhada para crescer se surgirem outras
-- configurações no futuro.

-- IDENTITY em vez de sequence manual — ver comentário da V1.
CREATE TABLE sr_config (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    atributos_padrao    CLOB            NOT NULL,
    atualizado_em       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    atualizado_por      NUMBER          NOT NULL,
    CONSTRAINT pk_sr_config PRIMARY KEY (id),
    CONSTRAINT fk_sr_config_usuario FOREIGN KEY (atualizado_por)
       REFERENCES sr_usuarios(id)
);

COMMENT ON TABLE  sr_config                  IS 'Configurações editáveis do sistema (hoje: atributos padrão do chat)';
COMMENT ON COLUMN sr_config.atributos_padrao IS 'JSON com array de strings — atributos usados quando o chat não identifica nenhum na mensagem do usuário';
COMMENT ON COLUMN sr_config.atualizado_por   IS 'FK para sr_usuarios — sempre um ADMIN, único perfil autorizado a alterar';

-- Linha única com os valores padrão atuais — lista completa dos 16
-- atributos padrão do SpecRadar (os 8 originais hardcoded em
-- ChatService + os 5 usados no vencedor do compare + os 3 novos do
-- brief oficial da Ford: modos_volante, modos_escapamento,
-- modos_amortecedor)
INSERT INTO sr_config (atributos_padrao, atualizado_por)
VALUES (
   '["motor","potencia","torque","transmissao","tracao","amortecedores","aceleracao","modos_conducao","farois","rodas_pneus","preco","consumo","dimensoes","modos_volante","modos_escapamento","modos_amortecedor"]',
   (SELECT id FROM sr_usuarios WHERE email = 'admin@specradar.com')
);

COMMIT;
